name = "pullback"
version = "0.1.0"
defaultTargets = ["pullback"]

[[lean_lib]]
name = "Pullback"

[[lean_exe]]
name = "pullback"
root = "Main"

[[require]]
name = "Qq"
git = "https://github.com/leanprover-community/quote4.git"


[[require]]
name = "mathlib"
scope = "leanprover-community"